  - name: Azure login (OIDC)
    uses: azure/login@v1
    with:
      client-id: da9d1344-0ea6-43b5-98cd-582f9432c418
      tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
      subscription-id: e48fa11c-15f3-48a0-a953-8d617222a070
      enable-AzPSSession: true

  - name: Download flag blob
    run: |
      # download blob using the logged-in identity (OIDC -> Azure AD -> managed identity)
      az storage blob download \
        --account-name iamazurelab3a3b1f4b3 \
        --container-name flag \
        --name flag.txt \
        --file flag.txt \
        --auth-mode login

  - name: Show flag
    run: |
      cat flag.txt
